plugins:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"
    - "node_modules/**/*"
    - "bin/*"
    - "tmp/**/*"

# Layout and formatting
Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Style
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

# Metrics
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

Metrics/ClassLength:
  Max: 160

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 25

# Naming
Naming/FileName:
  Exclude:
    - "lib/tapioca_dsl_compiler_store_model.rb"

# Gemspec
Gemspec/DevelopmentDependencies:
  Enabled: false

# RSpec
RSpec/ExampleLength:
  Max: 40

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4

RSpec/DescribeClass:
  Exclude:
    - "spec/integration/**/*"

RSpec/RemoveConst:
  Enabled: false
